export enum Verb {
  allows = "allows",
  calls = "calls",
  can = "can",
  canBe = "canBe",
  canBecome = "canBecome",
  canHave = "canHave",
  canHaveMany = "canHaveMany",
  canHaveOne = "canHaveOne",
  cannot = "cannot",
  dependsOn = "dependsOn",
  has = "has",
  is = "is",
  must = "must",
  mustHave = "mustHave",
  of = "of",
  responds = "responds",
  should = "should",
}

export enum InverseVerb {
  allows = "dependsOn",
  calledBy = "calls",
  calls = "calledBy",
  canBe = "is",
  canBeOf = "canHave",
  canHave = "canBeOf",
  dependsOn = "allows",
  has = "of",
  is = "canBe",
  mustBeOf = "mustHave",
  mustHave = "mustBeOf",
  of = "has",
  shouldBeOf = "shouldHave",
  shouldHave = "shouldBeOf",
}
